# Generated by Django 4.2.7 on 2025-08-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
