# Generated by Django 5.2.5 on 2025-08-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_add_currency_field'),
        ('debts', '0002_alter_debt_debtor_email'),
    ]

    operations = [
    ]
