# Generated by Django 4.2.7 on 2025-08-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iou_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iou',
            old_name='borrower_name',
            new_name='debtor',
        ),
    ]
