# Generated by Django 4.2.7 on 2025-08-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou_app', '0002_rename_borrower_name_iou_debtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iou',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
    ]
