# Generated by Django 5.2.5 on 2025-08-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iou_app', '0002_update_iou_model'),
        ('iou_app', '0003_alter_iou_currency'),
    ]

    operations = [
    ]
